version: "2"

services:
  app:
    build: example_golang/
    ports:
    - '8080:8080'
    networks:
    - ws
  prometheus:
    image: prom/prometheus:0.20.0
    ports:
    - '9090:9090'
    volumes:
    - './config:/etc/prometheus'
    - './data/prometheus:/prometheus'
    networks:
    - ws
  cadvisor:
    image: google/cadvisor:v0.23.2
    privileged: true
    ports:
    - '8081:8080'
    volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
    networks:
    - ws
  grafana:
    image: grafana/grafana:3.0.4
    restart: always
    ports:
    - '3000:3000'
    networks:
    - ws

networks:
  ws:
    driver: bridge
