version: "2"

services:
  app:
    build: example_golang/
    ports:
    - 8080
    networks:
    - ws
  prometheus:
    image: prom/prometheus:0.20.0
    command:
    - "-config.file=/etc/prometheus/prometheus.yml"
    - "-storage.local.path=/prometheus"
    - "-web.console.libraries=/etc/prometheus/console_libraries"
    - "-web.console.templates=/etc/prometheus/consoles"
    - "-alertmanager.url=http://alertmanager:9093"
    ports:
    - '9090:9090'
    volumes:
    - './config:/etc/prometheus'
    - './data/prometheus:/prometheus'
    networks:
    - ws
  cadvisor:
    image: google/cadvisor:v0.23.2
    privileged: true
    ports:
    - 8080
    volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
    networks:
    - ws
  grafana:
    image: grafana/grafana:3.0.4
    restart: always
    ports:
    - 3000:3000
    networks:
    - ws
  alertmanager:
    image: prom/alertmanager:0.2.1
    command:
    - "-config.file=/etc/alertmanager/alertmanager.yml"
    - "-storage.path=/alertmanager"
    volumes:
    - './data/alertmanager:/alertmanager'
    - './config:/etc/alertmanager'
    ports:
    - 9093:9093
    networks:
    - ws

networks:
  ws:
    driver: bridge
