version: "2"

services:
  prometheus:
    image: prom/prometheus
    ports:
    - '9090:9090'
    volumes:
    - './config:/etc/prometheus'
    - './storage:/prometheus'
    networks:
    - ws
  cadvisor:
    image: google/cadvisor
    privileged: true
    ports:
    - '8081:8080'
    volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
    networks:
    - ws

networks:
  ws:
    driver: bridge
